backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Seiten"
    files:
      - file: "src/content/home.md"
        label: "Startseite"
        name: "home"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Untertitel", name: "subtitle", widget: "string" }
          - { label: "Inhalt", name: "body", widget: "markdown" }